# Generated by Django 3.2 on 2023-11-11 12:05

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Оценка не может быть выше 10'), django.core.validators.MinValueValidator(1, message='Оценка не может быть ниже 1')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[reviews.validators.validate_year], verbose_name='Год'),
        ),
    ]
