# Generated by Django 3.2 on 2023-10-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='650315', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
