# Generated by Django 3.2 on 2023-11-12 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231111_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodelcategorygenre',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Оценка не может быть выше 10'), django.core.validators.MinValueValidator(1, message='Оценка не может быть ниже 1')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
