# Generated by Django 3.2 on 2023-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231031_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='629550', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
