# Generated by Django 3.2 on 2023-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20231102_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='756241', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
