# Generated by Django 3.2 on 2023-11-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20231106_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='281102', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
