# Generated by Django 3.2 on 2023-11-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20231104_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='662028', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
